from __future__ import annotations

from typing import Protocol

from movielib.domain.entities.film import Film
from movielib.domain.value_objects.telegram_id import TelegramId


class LibraryRepository(Protocol):
    async def add_to_watchlist(self, telegram_id: TelegramId, film_id: int) -> None: ...

    async def remove_from_watchlist(self, telegram_id: TelegramId, film_id: int) -> None: ...

    async def list_watchlist(self, telegram_id: TelegramId) -> list[Film]: ...

    async def add_favorite(self, telegram_id: TelegramId, film_id: int) -> None: ...

    async def remove_favorite(self, telegram_id: TelegramId, film_id: int) -> None: ...

    async def list_favorites(self, telegram_id: TelegramId) -> list[Film]: ...

    async def mark_watched(self, telegram_id: TelegramId, film_id: int) -> None: ...

    async def list_history(self, telegram_id: TelegramId, *, limit: int = 20) -> list[Film]: ...

    async def count_history(self, telegram_id: TelegramId) -> int: ...
