"""richer film metadata: genres, countries, duration, age rating, slogan

Revision ID: 270efc8ed066
Revises: c615f41ddc3d
Create Date: 2026-07-18 17:05:43.377548

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '270efc8ed066'
down_revision: str | None = 'c615f41ddc3d'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'films', sa.Column('genres', sa.String(length=256), nullable=False, server_default='')
    )
    op.add_column(
        'films', sa.Column('countries', sa.String(length=256), nullable=False, server_default='')
    )
    op.add_column('films', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('age_rating', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('slogan', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'slogan')
    op.drop_column('films', 'age_rating')
    op.drop_column('films', 'duration_minutes')
    op.drop_column('films', 'countries')
    op.drop_column('films', 'genres')
    # ### end Alembic commands ###
