"""personal library: watchlist, favorites, history, ratings, reviews, collections, search history

Revision ID: c615f41ddc3d
Revises: 15420d5046e9
Create Date: 2026-07-18 15:21:32.825075

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c615f41ddc3d'
down_revision: str | None = '15420d5046e9'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_items',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('collection_id', 'film_id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_collections_telegram_id'), 'collections', ['telegram_id'], unique=False
    )
    op.create_table('favorites',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('film_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'film_id')
    )
    op.create_table('ratings',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('film_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'film_id')
    )
    op.create_table('reviews',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('film_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'film_id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_search_history_telegram_id'), 'search_history', ['telegram_id'], unique=False
    )
    op.create_table('viewing_history',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('film_id', sa.BigInteger(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'film_id')
    )
    op.create_table('watchlist',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('film_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'film_id')
    )
    op.add_column('films', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'rating')
    op.drop_table('watchlist')
    op.drop_table('viewing_history')
    op.drop_index(op.f('ix_search_history_telegram_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_table('reviews')
    op.drop_table('ratings')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_collections_telegram_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_table('collection_items')
    # ### end Alembic commands ###
